services:
  backend_service:
    build:
      context: . # Root directory for build context
      dockerfile: backend/Dockerfile # Dockerfile is inside backend/
    container_name: upload_benchmark
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - .env:/app/.env
      - ./backend/templates:/app/backend/templates
      - ./backend/tmp:/app/backend/tmp
    networks:
      - talentsync_network

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - talentsync_network

  # mongodb_exporter:
  #   image: bitnami/mongodb-exporter:latest
  #   container_name: mongodb_exporter
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017
  #   ports:
  #     - "9216:9216"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - talentsync_network

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - talentsync_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # redis_exporter:
  #   image: oliver006/redis_exporter:latest
  #   container_name: redis_exporter
  #   command: --redis.addr=redis://redis:6379
  #   ports:
  #     - "9121:9121"
  #   depends_on:
  #     - redis
  #   networks:
  #     - talentsync_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - talentsync_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - .backend/monitoring/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - .backend/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - talentsync_network
    restart: always

networks:
  talentsync_network:

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
  redis_data:
