global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
